---
- name: Deploying with Kubernetes
  hosts: localhost
  tasks:

    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes 

    - name: Create Backend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes/backend-deployment.yaml') | from_yaml }}"

    - name: Create Ingress Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes/ingress-service.yaml') | from_yaml }}"

    - name: Create Backend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes/backend-service.yaml') | from_yaml }}"

    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes/frontend-deployment.yaml') | from_yaml }}" 

    - name: Create Frontend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes/frontend-service.yaml') | from_yaml }}" 